---
title: "Run 2"
author: "Andrew Neel"
date: "2025-08-17"
output: html_document
---

```{r}
library(dbscan)
library(dplyr)
library(stringr)
library(ggplot2)
library(ggcorrplot)
library(Rtsne)
```


```{r}
kNNdistplot(model.data, k = 8)
abline(h = 0.2, col = "red")
```
Because this project is mostly exploratory, I decided to run Moran's I again this time with lower epsilon and min points
```{r}
db2 <- dbscan(model.data, eps = 0.2, minPts = 8) 
```

evaluate
```{r}
summary(db2)
sum(db2$cluster == 0)
length(unique(db2$cluster)) - (0 %in% db2$cluster)
table(db2$cluster)
```

```{r}
pca <- prcomp(model.data)
df_plot <- as.data.frame(pca$x[, 1:2])
df_plot$cluster <- as.factor(db2$cluster)

ggplot(df_plot, aes(PC1, PC2, color = cluster)) +
  geom_point(alpha = 0.6) +
  labs(title = "Clusters Reduced by PCA") 
#ggsave("db2_clusters.png")
df_plot %>%
  filter(df_plot$cluster != 1) %>%
  ggplot(aes(PC1, PC2, color = cluster)) +
  geom_point(alpha = 0.6) +
  labs(title = "Clusters Reduced by PCA without Group 1") 
#ggsave("db2_clusters_minus1.png")
```


```{r}
outliers <- raw.data[db2$cluster == 0, ]
genre_counts <- table(outliers$main_genre)
genre_counts_filtered <- genre_counts[genre_counts > 2]
df_counts <- as.data.frame(genre_counts_filtered)
colnames(df_counts) <- c("genre", "count")

ggplot(df_counts, aes(x = genre, y = count)) +
  geom_bar(stat = "identity",fill = "steelblue") +
  geom_text(aes(label = count), vjust = -0.2) +
  labs(title = "Genres Appearing More Than Twice",
       x = "Genre",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#ggsave("outlier_genres2.png")

name_counts <- table(outliers$artist_name)
name_counts_filtered <- name_counts[name_counts > 2]
df_counts <- as.data.frame(name_counts_filtered)
colnames(df_counts) <- c("name", "count")

ggplot(df_counts, aes(x = name, y = count)) +
  geom_bar(stat = "identity",fill = "steelblue") +
  geom_text(aes(label = count), vjust = -0.2) +
  labs(title = "Artist Appearing More Than Twice",
       x = "Artist",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("outlier_Artist2.png")
```
```{r}
outliers <- raw.data[db2$cluster == 0, ]
for (col in cols) {
  
  p <- ggplot(outliers, aes_string(x = col)) +
    geom_density(fill = "steelblue", color = "white") +
    labs(title = paste("Distribution of", col), x = col, y = "Density") 
  print(p)
  
  filename <- paste0(col, "_outliers2.png")

  # Save plot
  #ggsave(filename, plot = p, width = 5, height = 4, dpi = 300)
}
```

```{r}
c2 <- raw.data[db2$cluster == 2, ]
genre_counts <- table(c2$main_genre)
genre_counts_filtered <- genre_counts[genre_counts > 0]
df_counts <- as.data.frame(genre_counts_filtered)
colnames(df_counts) <- c("genre", "count")

ggplot(df_counts, aes(x = genre, y = count)) +
  geom_bar(stat = "identity",fill = "steelblue") +
  geom_text(aes(label = count), vjust = -0.2) +
  labs(title = "Genres Appearing in Cluster 2",
       x = "Genre",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#ggsave("c2_genres2.png")

name_counts <- table(c2$artist_name)
name_counts_filtered <- name_counts[name_counts > 1]
df_counts <- as.data.frame(name_counts_filtered)
colnames(df_counts) <- c("name", "count")

ggplot(df_counts, aes(x = name, y = count)) +
  geom_bar(stat = "identity",fill = "steelblue") +
  geom_text(aes(label = count), vjust = -0.2) +
  labs(title = "Artist Appearing more than once in Cluster 2",
       x = "Artist",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("c2_Artist2.png")
```
```{r}
for (col in cols) {
  
  p <- ggplot(c2, aes_string(x = col)) +
    geom_density(fill = "steelblue", color = "white") +
    labs(title = paste("Distribution of", col), x = col, y = "Density") 
  print(p)
  
  # filename <- paste0(col, "_outliers.png")
  # 
  # # Save plot
  # ggsave(filename, plot = p, width = 5, height = 4, dpi = 300)
}
```

```{r}
c3 <- raw.data[db2$cluster == 5, ]
genre_counts <- table(c3$main_genre)
genre_counts_filtered <- genre_counts[genre_counts > 0]
df_counts <- as.data.frame(genre_counts_filtered)
colnames(df_counts) <- c("genre", "count")

ggplot(df_counts, aes(x = genre, y = count)) +
  geom_bar(stat = "identity",fill = "steelblue") +
  geom_text(aes(label = count), vjust = -0.2) +
  labs(title = "Genres Appearing in Cluster 5",
       x = "Genre",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#ggsave("c5_genres2.png")

name_counts <- table(c3$artist_name)
name_counts_filtered <- name_counts[name_counts > 0]
df_counts <- as.data.frame(name_counts_filtered)
colnames(df_counts) <- c("name", "count")

ggplot(df_counts, aes(x = name, y = count)) +
  geom_bar(stat = "identity",fill = "steelblue") +
  geom_text(aes(label = count), vjust = -0.2) +
  labs(title = "Artist Appearing in Cluster 5",
       x = "Artist",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("c5_Artist2.png")
```
```{r}
for (col in cols) {
  
  p <- ggplot(c3, aes_string(x = col)) +
    geom_density(fill = "steelblue", color = "white") +
    labs(title = paste("Distribution of", col), x = col, y = "Density") 
  print(p)
  
  # filename <- paste0(col, "_outliers.png")
  # 
  # # Save plot
  # ggsave(filename, plot = p, width = 5, height = 4, dpi = 300)
}
```

```{r}
ggplot(raw.data, aes(x=main_genre))+
  geom_bar(fill="steelblue")
```
